---
image: "alpine:latest"
.only-default: &only-default
  only:
    - master
    - wip
    - merge_requests

mr-settings:
  only:
    - merge_requests
  before_script:
    - apk -q add python3
  script:
    - wget -q "https://gitlab.com/postmarketOS/ci-common/-/raw/master/check_mr_settings.py"
    - python3 ./check_mr_settings.py

flake8:
  <<: *only-default
  before_script:
  - "apk -q add py3-pip"
  - "pip3 -q --disable-pip-version-check install flake8"
  script:
  - ".ci/flake8.sh"

vermin:
  <<: *only-default
  before_script:
  - "apk -q add py3-pip"
  - "pip3 -q --disable-pip-version-check install vermin"
  script:
  - ".ci/vermin.sh"

# Run same Alpine version as real bpo server
pytest:
  <<: *only-default
  image: "alpine:3.12"
  before_script:
  - wget "https://gitlab.com/postmarketOS/ci-common/-/raw/master/install_pmbootstrap.sh"
  # Install all python depends natively on Alpine for best performance, not with pip
  - sh ./install_pmbootstrap.sh \
        py3-flask \
        py3-pytest \
        py3-pytest-cov \
        py3-pytest-timeout \
        py3-requests \
        py3-sqlalchemy \
        xz
  - ln -s /tmp/pmbootstrap ../pmbootstrap
  - ln -s /home/pmos/.local/var/pmbootstrap/cache_git/pmaports ../pmbootstrap/aports
  script:
  - "su pmos -c '.ci/pytest.sh'"
  artifacts:
    when: "on_failure"
    paths:
    - "_html_out/index.html"
    - "_temp/local_job/current_task.sh"
    - "_temp/local_job_logs/*.txt"
    - "pytest.log"
    expire_in: "1 week"
