version: "2"

volumes:
  mariadb_data: {}

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: devsetup
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - mariadb_data:/var/lib/mysql/data
    ports:
      - 3306:3306

  bpo:
    image: bpo:latest
    depends_on:
      - db
    ports:
      - 80:8000
    volumes:
       - ../:/home/user/bpo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
     - db
    ports:
     - 8080:80
    volumes:
     - /sessions
