version: "2"

volumes:
  mariadb_data: {}

services:
  #~ db:
    #~ image: mariadb
    #~ environment:
      #~ MYSQL_ROOT_PASSWORD: devsetup
      #~ MYSQL_DATABASE: mysql
      #~ MYSQL_USER: mysql
      #~ MYSQL_PASSWORD: mysql
    #~ volumes:
      #~ - mariadb_data:/var/lib/mysql/data
    #~ ports:
      #~ - 3306:3306

  #~ bpo:
    #~ image: bpo:latest
    #~ depends_on:
      #~ - db
    #~ ports:
      #~ - 80:8000
    #~ volumes:
       #~ - ../:/home/user/bpo

  #~ phpmyadmin:
    #~ image: phpmyadmin/phpmyadmin:latest
    #~ depends_on:
     #~ - db
    #~ ports:
     #~ - 8080:80
    #~ volumes:
     #~ - /sessions

  redis:
    image: redis:latest
    expose:
     - 6379

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: devsetup
    expose:
      - 5432

  # We heard you like docker...
  docker:
    image: docker:dind
    privileged: true
    expose:
     - 2375
    volumes:
     - /var/lib/docker
    restart: on-failure

  builds.sr.ht:
    image: builds.sr.ht:latest
    depends_on:
     - docker
     - redis
     - postgres
    environment:
      DOCKER_HOST: tcp://docker:2375
      PYTHONUNBUFFERED: 1
    ports:
     - 8000:8000 # meta.sr.ht
     - 8002:8002 # builds.sr.ht
    volumes:
     - ./builds.sr.ht/patches:/patches:ro
